//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.04 at 08:21:37 AM MDT 
//


package gov.va.ehtac.hl7.hcs.policy.reference;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:hl7-org:v3}OrganizationTaggingRules" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v3}organizationConsentPolicyInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="orgName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="homeCommunityId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="usPrivacyLaw" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "organizationTaggingRules",
    "organizationConsentPolicyInfo"
})
@XmlRootElement(name = "OrganizationPolicy")
public class OrganizationPolicy {

    @XmlElement(name = "OrganizationTaggingRules")
    protected List<OrganizationTaggingRules> organizationTaggingRules;
    protected OrganizationConsentPolicyInfo organizationConsentPolicyInfo;
    @XmlAttribute(name = "orgName")
    protected String orgName;
    @XmlAttribute(name = "homeCommunityId")
    protected String homeCommunityId;
    @XmlAttribute(name = "usPrivacyLaw")
    protected String usPrivacyLaw;

    /**
     * Gets the value of the organizationTaggingRules property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the organizationTaggingRules property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrganizationTaggingRules().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrganizationTaggingRules }
     * 
     * 
     */
    public List<OrganizationTaggingRules> getOrganizationTaggingRules() {
        if (organizationTaggingRules == null) {
            organizationTaggingRules = new ArrayList<OrganizationTaggingRules>();
        }
        return this.organizationTaggingRules;
    }

    /**
     * Gets the value of the organizationConsentPolicyInfo property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationConsentPolicyInfo }
     *     
     */
    public OrganizationConsentPolicyInfo getOrganizationConsentPolicyInfo() {
        return organizationConsentPolicyInfo;
    }

    /**
     * Sets the value of the organizationConsentPolicyInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationConsentPolicyInfo }
     *     
     */
    public void setOrganizationConsentPolicyInfo(OrganizationConsentPolicyInfo value) {
        this.organizationConsentPolicyInfo = value;
    }

    /**
     * Gets the value of the orgName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * Sets the value of the orgName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgName(String value) {
        this.orgName = value;
    }

    /**
     * Gets the value of the homeCommunityId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHomeCommunityId() {
        return homeCommunityId;
    }

    /**
     * Sets the value of the homeCommunityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHomeCommunityId(String value) {
        this.homeCommunityId = value;
    }

    /**
     * Gets the value of the usPrivacyLaw property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsPrivacyLaw() {
        return usPrivacyLaw;
    }

    /**
     * Sets the value of the usPrivacyLaw property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsPrivacyLaw(String value) {
        this.usPrivacyLaw = value;
    }

}
