//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.04 at 08:21:37 AM MDT 
//


package gov.va.ehtac.hl7.hcs.policy.reference;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:hl7-org:v3}addr"/>
 *         &lt;element ref="{urn:hl7-org:v3}assignedAuthoringDevice"/>
 *         &lt;element ref="{urn:hl7-org:v3}defaultCustodianInfo"/>
 *         &lt;element ref="{urn:hl7-org:v3}humanReadibleText"/>
 *         &lt;element ref="{urn:hl7-org:v3}assignedAuthor"/>
 *         &lt;element ref="{urn:hl7-org:v3}defaultPatientDemographics"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "addr",
    "assignedAuthoringDevice",
    "defaultCustodianInfo",
    "humanReadibleText",
    "assignedAuthor",
    "defaultPatientDemographics"
})
@XmlRootElement(name = "organizationConsentPolicyInfo")
public class OrganizationConsentPolicyInfo {

    @XmlElement(required = true)
    protected Addr addr;
    @XmlElement(required = true)
    protected AssignedAuthoringDevice assignedAuthoringDevice;
    @XmlElement(required = true)
    protected DefaultCustodianInfo defaultCustodianInfo;
    @XmlElement(required = true)
    protected HumanReadibleText humanReadibleText;
    @XmlElement(required = true)
    protected AssignedAuthor assignedAuthor;
    @XmlElement(required = true)
    protected DefaultPatientDemographics defaultPatientDemographics;

    /**
     * Gets the value of the addr property.
     * 
     * @return
     *     possible object is
     *     {@link Addr }
     *     
     */
    public Addr getAddr() {
        return addr;
    }

    /**
     * Sets the value of the addr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Addr }
     *     
     */
    public void setAddr(Addr value) {
        this.addr = value;
    }

    /**
     * Gets the value of the assignedAuthoringDevice property.
     * 
     * @return
     *     possible object is
     *     {@link AssignedAuthoringDevice }
     *     
     */
    public AssignedAuthoringDevice getAssignedAuthoringDevice() {
        return assignedAuthoringDevice;
    }

    /**
     * Sets the value of the assignedAuthoringDevice property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssignedAuthoringDevice }
     *     
     */
    public void setAssignedAuthoringDevice(AssignedAuthoringDevice value) {
        this.assignedAuthoringDevice = value;
    }

    /**
     * Gets the value of the defaultCustodianInfo property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultCustodianInfo }
     *     
     */
    public DefaultCustodianInfo getDefaultCustodianInfo() {
        return defaultCustodianInfo;
    }

    /**
     * Sets the value of the defaultCustodianInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultCustodianInfo }
     *     
     */
    public void setDefaultCustodianInfo(DefaultCustodianInfo value) {
        this.defaultCustodianInfo = value;
    }

    /**
     * Gets the value of the humanReadibleText property.
     * 
     * @return
     *     possible object is
     *     {@link HumanReadibleText }
     *     
     */
    public HumanReadibleText getHumanReadibleText() {
        return humanReadibleText;
    }

    /**
     * Sets the value of the humanReadibleText property.
     * 
     * @param value
     *     allowed object is
     *     {@link HumanReadibleText }
     *     
     */
    public void setHumanReadibleText(HumanReadibleText value) {
        this.humanReadibleText = value;
    }

    /**
     * Gets the value of the assignedAuthor property.
     * 
     * @return
     *     possible object is
     *     {@link AssignedAuthor }
     *     
     */
    public AssignedAuthor getAssignedAuthor() {
        return assignedAuthor;
    }

    /**
     * Sets the value of the assignedAuthor property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssignedAuthor }
     *     
     */
    public void setAssignedAuthor(AssignedAuthor value) {
        this.assignedAuthor = value;
    }

    /**
     * Gets the value of the defaultPatientDemographics property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultPatientDemographics }
     *     
     */
    public DefaultPatientDemographics getDefaultPatientDemographics() {
        return defaultPatientDemographics;
    }

    /**
     * Sets the value of the defaultPatientDemographics property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultPatientDemographics }
     *     
     */
    public void setDefaultPatientDemographics(DefaultPatientDemographics value) {
        this.defaultPatientDemographics = value;
    }

}
