//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.04 at 08:21:37 AM MDT 
//


package gov.va.ehtac.hl7.hcs.policy.reference;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:hl7-org:v3}ObligationPolicy"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "obligationPolicy"
})
@XmlRootElement(name = "OrgObligationPolicyEntry")
public class OrgObligationPolicyEntry {

    @XmlElement(name = "ObligationPolicy", required = true)
    protected ObligationPolicy obligationPolicy;

    /**
     * Gets the value of the obligationPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link ObligationPolicy }
     *     
     */
    public ObligationPolicy getObligationPolicy() {
        return obligationPolicy;
    }

    /**
     * Sets the value of the obligationPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObligationPolicy }
     *     
     */
    public void setObligationPolicy(ObligationPolicy value) {
        this.obligationPolicy = value;
    }

}
